// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateProjectApiProjectsPostData, CreateProjectApiProjectsPostErrors, CreateProjectApiProjectsPostResponses, CreateProjectCommentApiProjectsProjectIdCommentsPostData, CreateProjectCommentApiProjectsProjectIdCommentsPostErrors, CreateProjectCommentApiProjectsProjectIdCommentsPostResponses, DeleteProjectApiProjectsIdDeleteData, DeleteProjectApiProjectsIdDeleteErrors, DeleteProjectApiProjectsIdDeleteResponses, DeleteProjectApiProjectsProjectIdCommentsIdDeleteData, DeleteProjectApiProjectsProjectIdCommentsIdDeleteErrors, DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponses, GetHealthApiHealthGetData, GetHealthApiHealthGetResponses, ReadProjectByIdApiProjectsIdGetData, ReadProjectByIdApiProjectsIdGetErrors, ReadProjectByIdApiProjectsIdGetResponses, ReadProjectCommentsApiProjectsProjectIdCommentsGetData, ReadProjectCommentsApiProjectsProjectIdCommentsGetErrors, ReadProjectCommentsApiProjectsProjectIdCommentsGetResponses, ReadProjectLogsApiProjectsProjectIdLogsGetData, ReadProjectLogsApiProjectsProjectIdLogsGetErrors, ReadProjectLogsApiProjectsProjectIdLogsGetResponses, ReadProjectsApiProjectsGetData, ReadProjectsApiProjectsGetErrors, ReadProjectsApiProjectsGetResponses, UpdateProjectApiProjectsIdPatchData, UpdateProjectApiProjectsIdPatchErrors, UpdateProjectApiProjectsIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Health
 */
export const getHealthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<GetHealthApiHealthGetData, ThrowOnError>) => (options?.client ?? client).get<GetHealthApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Read Projects
 *
 * Read projects.
 */
export const readProjectsApiProjectsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadProjectsApiProjectsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadProjectsApiProjectsGetResponses, ReadProjectsApiProjectsGetErrors, ThrowOnError>({ url: '/api/projects/', ...options });

/**
 * Create Project
 *
 * Create project.
 */
export const createProjectApiProjectsPost = <ThrowOnError extends boolean = false>(options: Options<CreateProjectApiProjectsPostData, ThrowOnError>) => (options.client ?? client).post<CreateProjectApiProjectsPostResponses, CreateProjectApiProjectsPostErrors, ThrowOnError>({
    url: '/api/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Project
 *
 * Delete a project
 */
export const deleteProjectApiProjectsIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectApiProjectsIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectApiProjectsIdDeleteResponses, DeleteProjectApiProjectsIdDeleteErrors, ThrowOnError>({ url: '/api/projects/{id}', ...options });

/**
 * Read Project By Id
 *
 * Read a specific project by id.
 */
export const readProjectByIdApiProjectsIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadProjectByIdApiProjectsIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadProjectByIdApiProjectsIdGetResponses, ReadProjectByIdApiProjectsIdGetErrors, ThrowOnError>({ url: '/api/projects/{id}', ...options });

/**
 * Update Project
 *
 * Update a project.
 */
export const updateProjectApiProjectsIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectApiProjectsIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateProjectApiProjectsIdPatchResponses, UpdateProjectApiProjectsIdPatchErrors, ThrowOnError>({
    url: '/api/projects/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Project Logs
 *
 * Read project logs.
 */
export const readProjectLogsApiProjectsProjectIdLogsGet = <ThrowOnError extends boolean = false>(options: Options<ReadProjectLogsApiProjectsProjectIdLogsGetData, ThrowOnError>) => (options.client ?? client).get<ReadProjectLogsApiProjectsProjectIdLogsGetResponses, ReadProjectLogsApiProjectsProjectIdLogsGetErrors, ThrowOnError>({ url: '/api/projects/{project_id}/logs', ...options });

/**
 * Read Project Comments
 *
 * Read project comments.
 */
export const readProjectCommentsApiProjectsProjectIdCommentsGet = <ThrowOnError extends boolean = false>(options: Options<ReadProjectCommentsApiProjectsProjectIdCommentsGetData, ThrowOnError>) => (options.client ?? client).get<ReadProjectCommentsApiProjectsProjectIdCommentsGetResponses, ReadProjectCommentsApiProjectsProjectIdCommentsGetErrors, ThrowOnError>({ url: '/api/projects/{project_id}/comments', ...options });

/**
 * Create Project Comment
 */
export const createProjectCommentApiProjectsProjectIdCommentsPost = <ThrowOnError extends boolean = false>(options: Options<CreateProjectCommentApiProjectsProjectIdCommentsPostData, ThrowOnError>) => (options.client ?? client).post<CreateProjectCommentApiProjectsProjectIdCommentsPostResponses, CreateProjectCommentApiProjectsProjectIdCommentsPostErrors, ThrowOnError>({
    url: '/api/projects/{project_id}/comments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Project
 *
 * Delete a project
 */
export const deleteProjectApiProjectsProjectIdCommentsIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectApiProjectsProjectIdCommentsIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponses, DeleteProjectApiProjectsProjectIdCommentsIdDeleteErrors, ThrowOnError>({ url: '/api/projects/{project_id}/comments/{id}', ...options });
