// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProjectChangeLog
 */
export type ProjectChangeLog = {
    /**
     * Id
     */
    id?: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Changed At
     */
    changed_at?: string | null;
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Old Value
     */
    old_value: string;
    /**
     * New Value
     */
    new_value: string;
};

/**
 * ProjectChangeLogListRead
 */
export type ProjectChangeLogListRead = {
    /**
     * Data
     */
    data: Array<ProjectChangeLog>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProjectCommentCreate
 */
export type ProjectCommentCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * ProjectCommentListRead
 */
export type ProjectCommentListRead = {
    /**
     * Data
     */
    data: Array<ProjectCommentRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProjectCommentRead
 */
export type ProjectCommentRead = {
    /**
     * Content
     */
    content: string;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: ProjectStatus;
};

/**
 * ProjectListRead
 */
export type ProjectListRead = {
    /**
     * Data
     */
    data: Array<ProjectRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: ProjectStatus;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectStatus
 */
export type ProjectStatus = 'planned' | 'active' | 'completed';

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: ProjectStatus | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetHealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthApiHealthGetResponses = {
    /**
     * Response Get Health Api Health Get
     *
     * Successful Response
     */
    200: unknown;
};

export type ReadProjectsApiProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/projects/';
};

export type ReadProjectsApiProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectsApiProjectsGetError = ReadProjectsApiProjectsGetErrors[keyof ReadProjectsApiProjectsGetErrors];

export type ReadProjectsApiProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectListRead;
};

export type ReadProjectsApiProjectsGetResponse = ReadProjectsApiProjectsGetResponses[keyof ReadProjectsApiProjectsGetResponses];

export type CreateProjectApiProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectApiProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiProjectsPostError = CreateProjectApiProjectsPostErrors[keyof CreateProjectApiProjectsPostErrors];

export type CreateProjectApiProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectApiProjectsPostResponse = CreateProjectApiProjectsPostResponses[keyof CreateProjectApiProjectsPostResponses];

export type DeleteProjectApiProjectsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type DeleteProjectApiProjectsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiProjectsIdDeleteError = DeleteProjectApiProjectsIdDeleteErrors[keyof DeleteProjectApiProjectsIdDeleteErrors];

export type DeleteProjectApiProjectsIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiProjectsIdDeleteResponse = DeleteProjectApiProjectsIdDeleteResponses[keyof DeleteProjectApiProjectsIdDeleteResponses];

export type ReadProjectByIdApiProjectsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type ReadProjectByIdApiProjectsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectByIdApiProjectsIdGetError = ReadProjectByIdApiProjectsIdGetErrors[keyof ReadProjectByIdApiProjectsIdGetErrors];

export type ReadProjectByIdApiProjectsIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type ReadProjectByIdApiProjectsIdGetResponse = ReadProjectByIdApiProjectsIdGetResponses[keyof ReadProjectByIdApiProjectsIdGetResponses];

export type UpdateProjectApiProjectsIdPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type UpdateProjectApiProjectsIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiProjectsIdPatchError = UpdateProjectApiProjectsIdPatchErrors[keyof UpdateProjectApiProjectsIdPatchErrors];

export type UpdateProjectApiProjectsIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectApiProjectsIdPatchResponse = UpdateProjectApiProjectsIdPatchResponses[keyof UpdateProjectApiProjectsIdPatchResponses];

export type ReadProjectLogsApiProjectsProjectIdLogsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/projects/{project_id}/logs';
};

export type ReadProjectLogsApiProjectsProjectIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectLogsApiProjectsProjectIdLogsGetError = ReadProjectLogsApiProjectsProjectIdLogsGetErrors[keyof ReadProjectLogsApiProjectsProjectIdLogsGetErrors];

export type ReadProjectLogsApiProjectsProjectIdLogsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectChangeLogListRead;
};

export type ReadProjectLogsApiProjectsProjectIdLogsGetResponse = ReadProjectLogsApiProjectsProjectIdLogsGetResponses[keyof ReadProjectLogsApiProjectsProjectIdLogsGetResponses];

export type ReadProjectCommentsApiProjectsProjectIdCommentsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/projects/{project_id}/comments';
};

export type ReadProjectCommentsApiProjectsProjectIdCommentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectCommentsApiProjectsProjectIdCommentsGetError = ReadProjectCommentsApiProjectsProjectIdCommentsGetErrors[keyof ReadProjectCommentsApiProjectsProjectIdCommentsGetErrors];

export type ReadProjectCommentsApiProjectsProjectIdCommentsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectCommentListRead;
};

export type ReadProjectCommentsApiProjectsProjectIdCommentsGetResponse = ReadProjectCommentsApiProjectsProjectIdCommentsGetResponses[keyof ReadProjectCommentsApiProjectsProjectIdCommentsGetResponses];

export type CreateProjectCommentApiProjectsProjectIdCommentsPostData = {
    body: ProjectCommentCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/comments';
};

export type CreateProjectCommentApiProjectsProjectIdCommentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectCommentApiProjectsProjectIdCommentsPostError = CreateProjectCommentApiProjectsProjectIdCommentsPostErrors[keyof CreateProjectCommentApiProjectsProjectIdCommentsPostErrors];

export type CreateProjectCommentApiProjectsProjectIdCommentsPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectCommentRead;
};

export type CreateProjectCommentApiProjectsProjectIdCommentsPostResponse = CreateProjectCommentApiProjectsProjectIdCommentsPostResponses[keyof CreateProjectCommentApiProjectsProjectIdCommentsPostResponses];

export type DeleteProjectApiProjectsProjectIdCommentsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/comments/{id}';
};

export type DeleteProjectApiProjectsProjectIdCommentsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiProjectsProjectIdCommentsIdDeleteError = DeleteProjectApiProjectsProjectIdCommentsIdDeleteErrors[keyof DeleteProjectApiProjectsProjectIdCommentsIdDeleteErrors];

export type DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponse = DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponses[keyof DeleteProjectApiProjectsProjectIdCommentsIdDeleteResponses];
