/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Fullstack project tracker
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRead } from './projectRead';

export interface ProjectListRead {
  data: ProjectRead[];
  count: number;
}
