/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Fullstack project tracker
 * OpenAPI spec version: 0.1.0
 */

export interface ProjectCommentRead {
  /** @maxLength 255 */
  content: string;
  id: string;
  project_id: string;
  created_at: string;
}
