"""Init tables in databases

Revision ID: b7a4471f0288
Revises: 
Create Date: 2026-04-23 22:39:39.049294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = 'b7a4471f0288'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='project_status').create(op.get_bind())
    op.create_table('projects',
    sa.Column('name', AutoString(length=255), nullable=False),
    sa.Column('description', AutoString(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'ACTIVE', 'COMPLETED', name='project_status', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_change_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_name', AutoString(), nullable=False),
    sa.Column('old_value', AutoString(), nullable=False),
    sa.Column('new_value', AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_change_logs_project_id'), 'project_change_logs', ['project_id'], unique=False)
    op.create_table('project_comments',
    sa.Column('content', AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comments_project_id'), 'project_comments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_comments_project_id'), table_name='project_comments')
    op.drop_table('project_comments')
    op.drop_index(op.f('ix_project_change_logs_project_id'), table_name='project_change_logs')
    op.drop_table('project_change_logs')
    op.drop_table('projects')
    sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='project_status').drop(op.get_bind())
    # ### end Alembic commands ###
