/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Fullstack project tracker
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';





/**
 * @summary Get Health
 */
export const getHealthApiV1HealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {


    return axios.default.get(
      `/api/v1/health`,options
    );
  }




export const getGetHealthApiV1HealthGetQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getGetHealthApiV1HealthGetQueryOptions = <TData = Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthApiV1HealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>> = ({ signal }) => getHealthApiV1HealthGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthApiV1HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>>
export type GetHealthApiV1HealthGetQueryError = AxiosError<unknown>


export function useGetHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthApiV1HealthGet>>,
          TError,
          Awaited<ReturnType<typeof getHealthApiV1HealthGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthApiV1HealthGet>>,
          TError,
          Awaited<ReturnType<typeof getHealthApiV1HealthGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Health
 */

export function useGetHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1HealthGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthApiV1HealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






