/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Fullstack project tracker
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HTTPValidationError,
  ProjectCreate,
  ProjectListRead,
  ProjectRead,
  ProjectUpdate,
  ReadProjectsApiV1ProjectsGetParams
} from '../models';





/**
 * Read projects.
 * @summary Read Projects
 */
export const readProjectsApiV1ProjectsGet = (
    params?: ReadProjectsApiV1ProjectsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectListRead>> => {


    return axios.default.get(
      `/api/v1/projects/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getReadProjectsApiV1ProjectsGetQueryKey = (params?: ReadProjectsApiV1ProjectsGetParams,) => {
    return [
    `/api/v1/projects/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadProjectsApiV1ProjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(params?: ReadProjectsApiV1ProjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProjectsApiV1ProjectsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>> = ({ signal }) => readProjectsApiV1ProjectsGet(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProjectsApiV1ProjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>>
export type ReadProjectsApiV1ProjectsGetQueryError = AxiosError<HTTPValidationError>


export function useReadProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(
 params: undefined |  ReadProjectsApiV1ProjectsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ReadProjectsApiV1ProjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ReadProjectsApiV1ProjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Projects
 */

export function useReadProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ReadProjectsApiV1ProjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectsApiV1ProjectsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProjectsApiV1ProjectsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create project.
 * @summary Create Project
 */
export const createProjectApiV1ProjectsPost = (
    projectCreate: ProjectCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectRead>> => {


    return axios.default.post(
      `/api/v1/projects/`,
      projectCreate,options
    );
  }



export const getCreateProjectApiV1ProjectsPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext> => {

const mutationKey = ['createProjectApiV1ProjectsPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, {data: ProjectCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProjectApiV1ProjectsPost(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectApiV1ProjectsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>>
    export type CreateProjectApiV1ProjectsPostMutationBody = ProjectCreate
    export type CreateProjectApiV1ProjectsPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Project
 */
export const useCreateProjectApiV1ProjectsPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>, TError,{data: ProjectCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProjectApiV1ProjectsPost>>,
        TError,
        {data: ProjectCreate},
        TContext
      > => {
      return useMutation(getCreateProjectApiV1ProjectsPostMutationOptions(options), queryClient);
    }
    /**
 * Read a specific project by id.
 * @summary Read Project By Id
 */
export const readProjectByIdApiV1ProjectsIdGet = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectRead>> => {


    return axios.default.get(
      `/api/v1/projects/${id}`,options
    );
  }




export const getReadProjectByIdApiV1ProjectsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/projects/${id}`
    ] as const;
    }


export const getReadProjectByIdApiV1ProjectsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError = AxiosError<HTTPValidationError>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProjectByIdApiV1ProjectsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>> = ({ signal }) => readProjectByIdApiV1ProjectsIdGet(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProjectByIdApiV1ProjectsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>>
export type ReadProjectByIdApiV1ProjectsIdGetQueryError = AxiosError<HTTPValidationError>


export function useReadProjectByIdApiV1ProjectsIdGet<TData = Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProjectByIdApiV1ProjectsIdGet<TData = Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProjectByIdApiV1ProjectsIdGet<TData = Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Project By Id
 */

export function useReadProjectByIdApiV1ProjectsIdGet<TData = Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProjectByIdApiV1ProjectsIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProjectByIdApiV1ProjectsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Update a project.
 * @summary Update Project
 */
export const updateProjectApiV1ProjectsIdPatch = (
    id: string,
    projectUpdate: ProjectUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectRead>> => {


    return axios.default.patch(
      `/api/v1/projects/${id}`,
      projectUpdate,options
    );
  }



export const getUpdateProjectApiV1ProjectsIdPatchMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>, TError,{id: string;data: ProjectUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>, TError,{id: string;data: ProjectUpdate}, TContext> => {

const mutationKey = ['updateProjectApiV1ProjectsIdPatch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>, {id: string;data: ProjectUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProjectApiV1ProjectsIdPatch(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectApiV1ProjectsIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>>
    export type UpdateProjectApiV1ProjectsIdPatchMutationBody = ProjectUpdate
    export type UpdateProjectApiV1ProjectsIdPatchMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Project
 */
export const useUpdateProjectApiV1ProjectsIdPatch = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>, TError,{id: string;data: ProjectUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProjectApiV1ProjectsIdPatch>>,
        TError,
        {id: string;data: ProjectUpdate},
        TContext
      > => {
      return useMutation(getUpdateProjectApiV1ProjectsIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a project
 * @summary Delete Project
 */
export const deleteProjectApiV1ProjectsIdDelete = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/v1/projects/${id}`,options
    );
  }



export const getDeleteProjectApiV1ProjectsIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProjectApiV1ProjectsIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProjectApiV1ProjectsIdDelete(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectApiV1ProjectsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>>

    export type DeleteProjectApiV1ProjectsIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Project
 */
export const useDeleteProjectApiV1ProjectsIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProjectApiV1ProjectsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteProjectApiV1ProjectsIdDeleteMutationOptions(options), queryClient);
    }
